apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: {{ .Values.topologyName }}
  namespace: c9s
spec:
  definition:
    containerlab: |
      name: {{ .Values.topologyName }}
      topology:
        nodes:
          {{- if ge .Values.nodeCount 1 }}
          router1:
            kind: {{ .Values.nodeKind }}
            image: {{ .Values.networkOsImage }}
          {{- end }}
          {{- if ge .Values.nodeCount 2 }}
          router2:
            kind: {{ .Values.nodeKind }}
            image: {{ .Values.networkOsImage }}
          {{- end }}
          {{- if ge .Values.nodeCount 3 }}
          router3:
            kind: {{ .Values.nodeKind }}
            image: {{ .Values.networkOsImage }}
          {{- end }}
          {{- if ge .Values.nodeCount 4 }}
          router4:
            kind: {{ .Values.nodeKind }}
            image: {{ .Values.networkOsImage }}
          {{- end }}
          {{- if ge .Values.nodeCount 5 }}
          router5:
            kind: {{ .Values.nodeKind }}
            image: {{ .Values.networkOsImage }}
          {{- end }}
        links:
          {{- if ge .Values.nodeCount 2 }}
          - endpoints: ["router1:eth2", "router2:eth2"]
          {{- end }}
          {{- if ge .Values.nodeCount 3 }}
          - endpoints: ["router1:eth3", "router3:eth2"]
          - endpoints: ["router2:eth3", "router3:eth3"]
          {{- end }}
          {{- if ge .Values.nodeCount 4 }}
          - endpoints: ["router1:eth4", "router4:eth2"]
          - endpoints: ["router2:eth4", "router4:eth3"]
          - endpoints: ["router3:eth4", "router4:eth4"]
          {{- end }}
          {{- if ge .Values.nodeCount 5 }}
          - endpoints: ["router1:eth5", "router5:eth2"]
          - endpoints: ["router2:eth5", "router5:eth3"]
          - endpoints: ["router3:eth5", "router5:eth4"]
          - endpoints: ["router4:eth5", "router5:eth5"]
          {{- end }}
